feature: support for .env variable that controls how many lines are visible on collapsed cards
arguflow/arguflow pull request #543
Opened 2023-09-30 21:48 UTC by Scorpil

Issue #523 @skeptrunedev

2023-09-30 22:13 UTC, densumesh requested changes

2023-09-30 22:13 UTC, densumesh commented on chat/src/components/ScoreCard.tsx
> +        style={{"-webkit-line-clamp": linesBeforeShowMore}}
We are using tailwind in this codebase, so please don't use the style param. Rather use the tailwind eqiviland and add it to the styles. i.e. https://tailwindcss.com/docs/line-clamp

2023-09-30 22:13 UTC, densumesh commented on search/src/components/ScoreCard.tsx
> +            style={{"-webkit-line-clamp": linesBeforeShowMore}}
Same as above comment

2023-09-30 22:13 UTC, densumesh commented on search/src/components/ScoreCard.tsx
> +            style={{"-webkit-line-clamp": linesBeforeShowMore}}
Same here

2023-09-30 22:15 UTC, densumesh commented
You are on the right track, just use tailwind and this will be an easy approve! Please also provide screenshots of working functionality if you can!

2023-09-30 23:32 UTC, Scorpil commented
I opted in for style approach because you can't have dynamic values in tailwind classes, since CSS files are created statically at build time https://tailwindcss.com/docs/content-configuration#dynamic-class-names

It's possible to configure a number of classes being _always_ included, but there are 2 problems with that:

- unused bundle are still included in a final bundle which goes agains the tailwinds principles
- only pre-defined values are supported, i.e. if values 1 through 10 are included, only those env variable values will have an effect.

_Maybe_ it's possible to use dotenv to read env variable in tailwind config on a build time to include single class... This would mean rebuild is required for variable value change to take effect, but otherwise should work. I considered it and decided that added complexity is not worth it compared to "style" approach. But if you do not agree I can try implementing it this way.

2023-10-01 00:37 UTC, densumesh commented
> I opted in for style approach because you can't have dynamic values in tailwind classes, since CSS files are created statically at build time https://tailwindcss.com/docs/content-configuration#dynamic-class-names
> 
> It's possible to configure a number of classes being _always_ included, but there are 2 problems with that:
> 
> * unused classes are still included in a final bundle which goes agains the tailwinds principles
> * only pre-defined values are supported, i.e. if classes with values 1 through 10 are included, only those env variable values will have an effect.
> 
> _Maybe_ it's possible to use dotenv to read env variable in tailwind config on a build time to include single class... This would mean rebuild is required for variable value change to take effect, but otherwise should work. I considered it and decided that added complexity is not worth it compared to "style" approach. But if you do not agree I can try implementing it this way.

You actually bring up a good point. Did not think of it that way

2023-10-01 02:21 UTC, skeptrunedev commented
Reviewing this again. Agreed on your approach actually.

2023-10-01 04:12 UTC, skeptrunedev approved these changes
@Scorpil you actually crushed this issue, nice work man! Don't forget to leave a star if you haven't yet :heart: . 

I wound up catching another bug while reviewing w/ not having the gradient mask package on `chat` that I fixed. Then I also just ran prettier. No worries there, those things were not requirements in the issue. 

There is one thing I still don't like. We have to leave the tailwind `line-clamp` style since it is a utility class that adds more styles than just the lines - https://tailwindcss.com/docs/line-clamp - and I don't know. It just feels bad. Not quite sure how to fix it, but something to think about if you ever hit this in the future. Thanks for your work man!

2023-10-01 04:12 UTC, merged